### ISSUE TITLE
Ignore hyperlinks in comments

### ISSUE THREAD

**Issue by joeyvanlierop** [joeyvanlierop/xkcdbot#12]
The bot currently matches numbers found in hyperlinks such as in [this case](https://www.reddit.com/r/xkcd/comments/eut0e2/xkcd_2260_reaction_maps/ffrd5jo/). This should be explicitly avoided.

**Comment by Nyhilo** [comment]
The way I see it, this can be handle one of two ways.

Either we can ignore matches in urls specifically, or we can make the regex much tighter in general.

I'm thinking 
```python
(?i)(?x)                # Ignore case, comment mode
(?<= ^! | \s! | \(!     # Must be preceded by whitespace, line start, or open paren
    ^\# | \s\# | \(! )  # and an exlaimation mark or pound sign
\d                      # Match the following numbers
(?= \b )                # Match only on a word boundary
```

(?<= ^! | \s! | \(! ^\# | \s\# | \(! )
    This ensures that there is a white space or open parenthesis before the code character.
    It makes sure the match only happens if the pattern isn't embedded inside other text (or is in parentheses).

(?= \b )
    This ensures that the end of the match is only on a word boundary. This allows for punctuation, whitespace, etc. But will prevent matching on accidental junk like !123&adf8 or whatever.

I would also change \d to \d{1,4}
    This ensures that we only match if the number after the bang is 1 to 4 digits long. If Randall keeps updating weekly, it will take about 148 years before we reach a comic #10000. Limiting the number of digits being matched will greatly reduce false negatives.

This regex would match on the following:
    !1234
    #1234
    Let's look at !1234
    Let's look at #1234.
    ...looking at the comic in question (!1234) we can say that...

But not:
    I spent $123.45 today
    Comic #12345 doesn't exist
    website.com/?=!1234
    website.com/?=#1234
    I have made a mistake referencing this xkcd#1234
    some junk -> a^698f7%s@ !123a*b@3

**Comment by joeyvanlierop** [comment]
Great suggestions! Would you mind making a pull request with some updated tests?

**Comment by Nyhilo** [comment]
Added in #14.

**Comment by Nyhilo** [comment]
Hold up, you said "with tests". Whoops...

**Comment by Nyhilo** [comment]
Alright, the PR has been updated with test cases. See there for additional info.

**Comment by joeyvanlierop** [comment]
Closed in #15

**Comment by joeyvanlierop** [comment]
After poking around with the code in #15 , I ran into some issues. I believe there are some regex nuances in Python regarding look-behind. The tests are throwing this error: 

`re.error: look-behind requires fixed-width pattern`.

**Comment by Nyhilo** [comment]
Ah well, that's what the tests are supposed to be for I guess, right?

I might pick this back up when I have more time to do it correctly. Cheers until then!

**Comment by lcheng49** [comment]
I've updated the code to not match !(number) or #(number) that occur in the middle of a string or url and have added tests to the testing file.

**Comment by joeyvanlierop** [comment]
Cloased by #27
