### ISSUE TITLE
Call bot with "Relevant xkcd: {number}"

### ISSUE THREAD

**Issue by joeyvanlierop** [joeyvanlierop/xkcdbot#13]
Add the ability to call the bot by commenting: 
`Relevant xkcd: {number}`

Example comment:
`Relevant xkcd: 327`

The two streams that are currently being analyzed are:
 - Comments in /r/xkcd
 - Inbox items (username mentions, private messages)

This change will require analyzing comments from outside /r/xkcd which is currently not implemented. It will also require a new matching pattern.

**Comment by HaydoMaydo** [comment]
I submitted a pull request for this issue. I am new to contributing to open source projects, so please let me know if I am doing something wrong.

**Comment by joeyvanlierop** [comment]
Thanks for the contribution! Before I merge this, would you be able to implement some tests to ensure there are no obvious issues?

**Comment by sadoe** [comment]
There's a PR for this at #25.

**Comment by joeyvanlierop** [comment]
Closed by #25
