### ISSUE TITLE
Is a backlog/queue script needed?

### ISSUE THREAD

**Issue by sadoe** [joeyvanlierop/xkcdbot#22]
Since we are setting **skip_existing** to **False** when initializing the comment stream, even if the bot was down for whatever reason, when it goes back online, it should be able to respond to all the comments chronologically and eventually catch up. Am I wrong?

Sorry if It's a dumb issue I'm new to Github

**Comment by joeyvanlierop** [comment]
I believe you are correct. I had **skip_existing** to **True** at the time and as you mentioned, setting it to **False** has corrected the issue.
