### ISSUE TITLE
I think I might have broken your bot

### ISSUE THREAD

**Issue by plokmijnuhby** [joeyvanlierop/xkcdbot#28]
https://www.reddit.com/r/ProgrammerHumor/comments/g9u3yh/oh_so_this_is_how_to_reproduce_that_weird_issue/foxppns/?context=0

**Comment by joeyvanlierop** [comment]
Thankfully the bot seems to be running completely fine right now.

There are a few measures in place to ensure that the bot is not abused:
 - https://github.com/joeyvanlierop/xkcdbot/blob/7b23bedebe804fa5e5c3c5c80648019dd2db7916/bot/bot.py#L112
 - https://github.com/joeyvanlierop/xkcdbot/blob/7b23bedebe804fa5e5c3c5c80648019dd2db7916/bot/bot.py#L128
 - https://github.com/joeyvanlierop/xkcdbot/blob/7b23bedebe804fa5e5c3c5c80648019dd2db7916/bot/bot.py#L443
