### ISSUE TITLE
Handle range of comics

### ISSUE THREAD

**Issue by joeyvanlierop** [joeyvanlierop/xkcdbot#6]
Implement the ability to comment "!585...590" and return the comics with id's 585, 586, 587, 588, 589, 560. More information can be found [here](https://www.reddit.com/r/xkcd/comments/erydbl/introducing_ubobbytablesbot/ff7s6zt/).

**Comment by cj81499** [comment]
Should there be a limit on the number of comics in the range? It seems like a bad idea to let users request thousands of comics.

**Comment by joeyvanlierop** [comment]
The bot currently truncates the list of responses in [this line](https://github.com/joeyvanlierop/xkcdbot/blob/64163dac5b92f83c5e82ec2146e5bd25f3ddaf09/bot/bot.py#L329) and also has a break statement in [this line](https://github.com/joeyvanlierop/xkcdbot/blob/64163dac5b92f83c5e82ec2146e5bd25f3ddaf09/bot/bot.py#L107), however it might be a good idea to implement another check/break within the method that would handle a range of comics.

**Comment by sadoe** [comment]
@joeyvanlierop I just started working on this. What should our approach be when a range is entered backwards? e.g. "!590...550"

**Comment by joeyvanlierop** [comment]
It's up to you. I don't think it would be too difficult to make it work in reverse, however if the solution becomes convoluted or very unintuitive, feel free to ignore it. 

Note: There is currently an open pull request that worked on this. Check it out [here ](https://github.com/joeyvanlierop/xkcdbot/pull/19)if you want some guidance.

**Comment by joeyvanlierop** [comment]
Solved in #24
