### ISSUE TITLE
Return random comic

### ISSUE THREAD

**Issue by joeyvanlierop** [joeyvanlierop/xkcdbot#7]
Implement the ability to comment "!random" or "#random" to return a random comic. More information can be found [here](https://www.reddit.com/r/xkcd/comments/erydbl/introducing_ubobbytablesbot/ff7wmeh/).

**Comment by menarulalam** [comment]
Can I work on this? I'm a bit new so I would like to gain some experience.

**Comment by joeyvanlierop** [comment]
Absolutely. Feel free to clone the project and issue a pull request if you are able to get it working. Good luck!

**Comment by joeyvanlierop** [comment]
Closed by #18
