### ISSUE TITLE
Comic #404 is not displayed properly

### ISSUE THREAD

**Issue by jmeberlein** [joeyvanlierop/xkcdbot#9]
`find_comic(self, number)` currently assumes that if the server returns a 404, that the comic doesn't actually exist and thus that the bot shouldn't display anything. However, as we all know, Randall purposefully skipped comic 404 as a nerdy joke, so that 404 error should be handled special.

**Comment by joeyvanlierop** [comment]
Fixed by #10

**Comment by joeyvanlierop** [comment]
For future reference, checking if comic 404 was referenced required a check against the string "404" rather than the number 404. 

This was fixed in ed7c063d8f74932fae2cc768ab5d15ea36391388
